#ifndef SUPERSCALAR_VERSION_H
#define SUPERSCALAR_VERSION_H

#define SUPERSCALAR_VERSION_MAJOR 0
#define SUPERSCALAR_VERSION_MINOR 1
#define SUPERSCALAR_VERSION_PATCH 5
#define SUPERSCALAR_VERSION "0.1.5"

#endif /* SUPERSCALAR_VERSION_H */
