#ifndef SUPERSCALAR_VERSION_H
#define SUPERSCALAR_VERSION_H

#define SUPERSCALAR_VERSION_MAJOR 0
#define SUPERSCALAR_VERSION_MINOR 1
#define SUPERSCALAR_VERSION_PATCH 0
#define SUPERSCALAR_VERSION "0.1.0"

#endif /* SUPERSCALAR_VERSION_H */
